name: SPHERE
channels:
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.47.0=hadc24fc_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=he02047a_1
  - openssl=3.4.0=hb9d3cd8_0
  - pip=24.3.1=pyh8b19718_0
  - python=3.8.20=h4a871b0_2_cpython
  - readline=8.2=h8228510_1
  - setuptools=75.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - anndata==0.9.2
      - asttokens==3.0.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - backcall==0.2.0
      - bamnostic==1.1.10
      - biocframe==0.5.11
      - biocutils==0.1.6
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - comm==0.2.3
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.20
      - decorator==5.2.1
      - episcanpy==0.4.0
      - executing==2.2.1
      - filelock==3.13.1
      - fonttools==4.54.1
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - genomicranges==0.4.34
      - get-annotations==0.1.2
      - h5py==3.11.0
      - harmonypy==0.0.10
      - idna==3.4
      - igraph==0.11.8
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - intervaltree==3.1.0
      - ipykernel==6.29.5
      - ipython==8.12.3
      - iranges==0.2.12
      - jedi==0.19.2
      - jinja2==3.1.3
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - keras-applications==1.0.8
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.7
      - kneed==0.8.5
      - legacy-api-wrap==1.4.1
      - leidenalg==0.10.2
      - llvmlite==0.41.1
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - multidict==6.1.0
      - natsort==8.4.0
      - ncls==0.0.68
      - nest-asyncio==1.6.0
      - networkx==3.0
      - numba==0.58.1
      - numpy==1.24.1
      - packaging==24.2
      - pandas==2.0.3
      - parso==0.8.6
      - patsy==1.0.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - platformdirs==4.3.6
      - polars==1.8.2
      - pot==0.9.5
      - prompt-toolkit==3.0.52
      - propcache==0.2.0
      - psutil==7.2.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pynndescent==0.5.13
      - pyparsing==3.1.4
      - pysam==0.22.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==27.1.0
      - requests==2.28.1
      - ruptures==1.1.9
      - scanpy==1.9.8
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - session-info==1.0.0
      - setuptools-scm==8.1.0
      - six==1.17.0
      - sortedcontainers==2.4.0
      - stack-data==0.6.3
      - statsmodels==0.14.1
      - stdlib-list==0.10.0
      - sympy==1.13.1
      - tbb==2022.0.0
      - tcmlib==1.2.0
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tomli==2.2.1
      - torch==2.1.0+cu121
      - torch-cluster==1.6.3+pt21cu121
      - torch-geometric==2.6.1
      - torchaudio==2.1.0+cu121
      - torchvision==0.16.0+cu121
      - tornado==6.4.2
      - tqdm==4.67.0
      - traitlets==5.14.3
      - triton==2.1.0
      - typing-extensions==4.9.0
      - tzdata==2024.2
      - umap-learn==0.5.7
      - urllib3==1.26.13
      - wcwidth==0.6.0
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /home/yuzhuohan/miniconda3/envs/SPHERE1
